# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75eca7643f02fc181f8a8b55477988a2db4f1fc9e6881149f956914695219e61744188db101331fd00890ade4cb125f7d5ad0652f98cfd7208e06b8dda51abf9

test:
  secret_key_base: 8c26b764e4d36cd1e3005e3eb771f29ee1e4dacaf29e363105902ce2c06c9521a51117371647ed8d6bbd5150a04808c5b52d33f28c80fec42196e8163df354ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
